---
- hosts: all
  user: vagrant
  sudo: True
  roles:
   - geerlingguy.php
   - geerlingguy.git
   - geerlingguy.mysql
   - grlee.apache_ubuntu
   - geerlingguy.composer
   - mbasanta.pip
   - lesmyrmidons.mongodb
